---
title: "models"
author: "REFG"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse); theme_set(theme_minimal())
library(kableExtra)
library(recipes)
library(lavaan)
library(stargazer)
library(mice)
library(sjPlot)
library(psfmi)
library(readr)
```
```{r}

cps <- read_csv("cps.csv")

require(finalfit)

ff_glimpse(cps)$Continuous[,c('n','missing_percent')]



```

```{r mice}
p_missing <- unlist(lapply(cps, function(x) sum(is.na(x))))/nrow(cps)
sort(p_missing[p_missing > 0], decreasing = TRUE)

md.pattern(cps)
p <- md.pairs(cps)
p

# We run the mice code with 0 iterations 

imp <- mice(cps, maxit=0)


# Extract predictorMatrix and methods of imputation 

predM <- imp$predictorMatrix
meth <- imp$method

# With this command, we tell mice to impute the data, create 5
# datasets, use predM as the predictor matrix and don't print the imputation
# process. If you would like to see the process, set print as TRUE

imp2 <- mice(cps, maxit = 20, 
             predictorMatrix = predM, 
             method = meth, print =  FALSE)

#Finally, we need to run the regression on each of the 5 datasets and pool the estimates together to get average regression coefficients and correct standard errors. The with function in the mice package allows us to do this.

# First, turn the datasets into long format
cps_long <- mice::complete(imp2, action="long", include = TRUE)

# Convert back to mids type - mice can work with this type
cps_long_mids<-as.mids(cps_long)


```

```{r}
dfcps<-complete(imp2)

write.csv(dfcps, file= "dfcps.csv")
```

```{r imputed}
# ggmice(imp2, aes(x = .imp, y = Internalizing )) + 
#   geom_jitter(height = 0, width = 0.25) +
#   geom_boxplot(width = 0.5, size = 1, alpha = 0.75, outlier.shape = NA) +
#   labs(x = "Imputation number", y = "Internalizing Score")
# 
# ggmice(imp2, aes(x = .imp, y = Externalizing)) + 
#   geom_jitter(height = 0, width = 0.25) +
#   geom_boxplot(width = 0.5, size = 1, alpha = 0.75, outlier.shape = NA) +
#   labs(x = "Imputation number", y = "Externalizing Score")
```



```{r hyp2}

fitimpadhd <- glm(adhd ~ Poverty + Internalizing+ Externalizing+ Ethnicity+ Gender, family=binomial	(link = "logit"), data=dfcps)

f1 <- summary(fitimpadhd)

fitimpasd <- glm(asd ~ Poverty + Internalizing+ Externalizing+ Ethnicity+ Gender,family=binomial	(link = "logit"), data=dfcps)

f2 <- summary(fitimpasd)

fitimpasthma <- glm(asthma ~ Poverty + Internalizing+ Externalizing+ Ethnicity+ Gender,family=binomial	(link = "logit"), data=dfcps)

f3 <- summary(fitimpasthma)

fitimpweight <- glm(weight ~ Poverty + Internalizing+ Externalizing+ Ethnicity+ Gender,family=binomial	(link = "logit"), data=dfcps)

f4 <- summary(fitimpweight)

fitimpanxdep <- glm(anxdep ~ Poverty + Internalizing+ Externalizing+ Ethnicity+ Gender, family=binomial	(link = "logit"), data=dfcps)

f5 <- summary(fitimpanxdep)

fs <- cbind(f1,f2,f3)
fss <- cbind(f4,f5)


```
```{r hyp1}
fitimpext <- lm(Externalizing ~ Poverty + Internalizing+  Ethnicity+ Gender, data=dfcps)

f6<-summary(fitimpext)

fitimpint <- lm(Internalizing ~ Poverty + Externalizing+ Ethnicity+ Gender, data=dfcps)

f7<-summary(fitimpint)

fs1<- cbind(f6,f7)



```

```{r pred-adhd}
pred_prob_adhd<-predict(fitimpadhd, type='response')
dfcps$pred_prob_adhd <- ifelse(pred_prob_adhd>.5,1,0)
tab <- table(dfcps$pred_prob_adhd,
             dfcps$adhd,
             dnn = c('Predicted','Observed'))
#accuracy

(tab[2,2] + tab[1,1])/(tab[1,1]+tab[2,2]+tab[1,2]+tab[2,1])
# True Negative Rate

tab[1,1]/(tab[1,1]+tab[1,2])
# True Positive Rate

tab[2,2]/(tab[2,1]+tab[2,2])

# Precision

tab[2,2]/(tab[1,2]+tab[2,2])
```
```{r pred-asd}
pred_prob_asd<-predict(fitimpasd, type='response')
dfcps$pred_prob_asd <- ifelse(pred_prob_asd>.5,1,0)
tab <- table(dfcps$pred_prob_asd,
             dfcps$asd,
             dnn = c('Predicted','Observed'))
tn <- tab[1,1]
tp <- tab[2,2]
fp <- tab[2,1]
fn <- tab[1,2]
acc <- (tp + tn)/(tp+tn+fp+fn)
acc
# True Negative Rate

tab[1,1]/(tab[1,1]+tab[1,2])
# True Positive Rate

tab[2,2]/(tab[2,1]+tab[2,2])

# Precision

tab[2,2]/(tab[1,2]+tab[2,2])
# True Negative Rate

tab[1,1]/(tab[1,1]+tab[1,2])
# True Positive Rate

tab[2,2]/(tab[2,1]+tab[2,2])

# Precision

tab[2,2]/(tab[1,2]+tab[2,2])
```
```{r pred-weight}
pred_prob_weight<-predict(fitimpweight, type='response')
dfcps$pred_prob_weight <- ifelse(pred_prob_weight>.5,1,0)
tab <- table(dfcps$pred_prob_weight,
             dfcps$weight,
             dnn = c('Predicted','Observed'))

#accuracy

(tab[2,2] + tab[1,1])/(tab[1,1]+tab[2,2]+tab[1,2]+tab[2,1])
# True Negative Rate

tab[1,1]/(tab[1,1]+tab[1,2])
# True Positive Rate

tab[2,2]/(tab[2,1]+tab[2,2])

# Precision

tab[2,2]/(tab[1,2]+tab[2,2])
```
```{r pred-asthma}
pred_prob_asthma<-predict(fitimpasthma, type='response')
dfcps$pred_prob_asthma <- ifelse(pred_prob_asthma>.5,1,0)
tab <- table(dfcps$pred_prob_asthma,
             dfcps$asthma,
             dnn = c('Predicted','Observed'))
tn <- tab[1,1]
tp <- tab[2,2]
fp <- tab[2,1]
fn <- tab[1,2]
acc <- (tp + tn)/(tp+tn+fp+fn)
acc

# True Negative Rate

tab[1,1]/(tab[1,1]+tab[1,2])
# True Positive Rate

tab[2,2]/(tab[2,1]+tab[2,2])

# Precision

tab[2,2]/(tab[1,2]+tab[2,2])
```
```{r pred-anxdep}
pred_prob_anxdep<-predict(fitimpanxdep, type='response')
dfcps$pred_prob_anxdep <- ifelse(pred_prob_anxdep>.5,1,0)
tab <- table(dfcps$pred_prob_anxdep,
             dfcps$anxdep,
             dnn = c('Predicted','Observed'))
#accuracy

(tab[2,2] + tab[1,1])/(tab[1,1]+tab[2,2]+tab[1,2]+tab[2,1])
# True Negative Rate

tab[1,1]/(tab[1,1]+tab[1,2])
# True Positive Rate

tab[2,2]/(tab[2,1]+tab[2,2])

# Precision

tab[2,2]/(tab[1,2]+tab[2,2])
```
```{r pred-int}
pred_prob_internalizing<-predict(fitimpint)
outs  <- dfcps$Internalizing
preds <- pred_prob_internalizing
mae<-mean(abs(outs-preds))
rmse<-sqrt(mean(outs - preds)^2)
rsq <- cor(outs, preds)^2

```
```{r pred-ext}
pred_prob_externalizing<-predict(fitimpext)
outs  <- dfcps$Externalizing
preds <- pred_prob_externalizing
mae<-mean(abs(outs-preds))
mae
rmse<-sqrt(mean(outs - preds)^2)
rsq <- cor(outs, preds)^2
```

```{r demo-table}
demo <- cps %>% 
	select(Gender, Poverty, Ethnicity, Externalizing, Internalizing) %>% 
	psych::describe(na.rm=T) %>% as.data.frame() %>% 
	select(-mad, -trimmed, -vars) %>% 
	kable(caption = "Sample Demographics",digits = 2) %>% 
	kable_classic() %>%
	kable_styling(full_width = T) 

save_kable(demo, file = "demo.png")

```

```{r model-table}
tab <- kbl(fs, caption = "Model Statistics",digits=2) %>%
  kable_classic() %>%
	kable_styling(full_width = T) %>% 
  add_header_above(c("weight" = 6, "ASD" = 6, "Asthma" = 6)) 

tab2 <- kbl(fss, caption = "Model Statistics",digits=2) %>%
  kable_classic() %>%
	kable_styling(full_width = T) %>% 
  add_header_above(c( "Overweight" = 6, "Anxiety/Depression" = 6)) 



save_kable(tab, file = "tab.png",
             zoom = 1.5)
save_kable(tab2, file = "tab2.png",
             zoom = 1.5)


```
```{r}
tab1 <- kbl(fs1, caption = "Model Statistics",digits=2) %>%
  kable_classic() %>%
	kable_styling(full_width = T) %>% 
  add_header_above(c("Externalizing" = 6, "Internalizing" = 6))

save_kable(tab1, file = "tab1.png",
             zoom = 1.5)
```
